feat: added role assignments to groups
blinqas/station pull request #126
Opened 2024-06-05 13:06 UTC by SanderBlom

# Added role assignments to groups

## Description
Users should now be able to assign different RBAC roles to the group during creation. 

## Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Other

## Testing
See the testing [docs](../tests/readme.md) for more information about how to test your code 
- [x] Performed a local `terraform plan`, `apply`, and `destroy` to validate changes.
- [x] All tests are passing.
- [x] Added, updated, or removed tests when appropriate

## Checklist

Before submitting this PR, please ensure the following:

- [x] My commits follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) style guide
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings. I have ran `terraform validate` in the root module and all sub modules where I have made changes

## Additional Information

N.A

---

Thank you for contributing to Station!

2024-06-05 16:30 UTC, kimfy requested changes

2024-06-05 16:30 UTC, kimfy commented on variables.tf
> +      assign_to_workload_principal           = optional(bool)
Is there a reason to include `assign_to_workload_principal` on a group role assignment?

2024-06-05 16:30 UTC, kimfy commented on variables.tf
> +      role_definition_name                   = optional(string) #Either this or the above must be provided
nitpick: comment is fluff

2024-06-05 16:30 UTC, kimfy commented on variables.tf
> +      scope                                  = optional(string) #Sets scope to current subscription if empty
nitpick: comment is fluff

2024-06-05 16:30 UTC, kimfy commented on variables.tf
> +      delegated_managed_identity_resource_id = optional(string)
`delegated_managed_identity_resource_id`: For a group, why is this necessary?

2024-06-05 16:30 UTC, kimfy commented on group/group.tf
> +data "azurerm_client_config" "current" {}
Including `data "azurerm_client_config" "current" {}` in here is a bad idea and negates the previous PRs which aims to reduce the amount of data sources managed with Terraform Cloud.

I suggest this is resolved on caller level (`/groups.tf`)

2024-06-05 16:30 UTC, kimfy commented on group/group.tf
> +resource "azurerm_role_assignment" "roles" {
I think this resource should be its own file called `role_assignments.tf`.

2024-06-05 16:30 UTC, kimfy commented on group/outputs.tf
> +output "group_with_roles" {
I believe this adds a lot of overhead in terms of managing this output. I suggest just adding another output for role assignments:

```terraform
output "role_assignments" {
  value = azurerm_role_assignment.roles 
}
```

2024-06-06 08:11 UTC, SanderBlom commented
@kimfy Can you verify the new changes?

2024-06-14 07:26 UTC, kimfy commented
Resolves #106

2024-06-18 12:41 UTC, kimfy approved these changes

2024-06-18 12:41 UTC, merged