feat: Added support for directory role assignment
blinqas/station pull request #129
Opened 2024-06-06 13:51 UTC by SanderBlom

# Added support for directory role assignment

## Description

This PR adds support for assigning Entra ID directory roles for both the workload identity (the user assigned identity that provisions the infrastructure) and during the creation of new user assigned identities. 

This PR resolves #104 

## Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Other

## Testing
See the testing [docs](../tests/readme.md) for more information about how to test your code 
- [x] Performed a local `terraform plan`, `apply`, and `destroy` to validate changes.
- [x] All tests are passing.
- [x] Added, updated, or removed tests when appropriate

## Checklist

Before submitting this PR, please ensure the following:

- [x] My commits follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) style guide
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings. I have ran `terraform validate` in the root module and all sub modules where I have made changes

## Additional Information

- I can not get the app scope deployment to work.

---

Thank you for contributing to Station!

2024-06-07 12:08 UTC, kimfy requested changes
This looks incomplete and I'd much rather see this incorporated when the `identity` variable is implemented.

2024-06-07 12:08 UTC, kimfy commented on variables.tf
> +  description = <<EOF
Missing description for `role_name`, `principal_object_id`, `app_scope_id`, `directory_scope_id`. (copy from provider documentation).

2024-06-07 12:08 UTC, kimfy commented on variables.tf
> +    - assign_to_workload_principal assigns the role to the workload identity. Can not be used with principal_id.
This isn't an option according to the type.

2024-06-07 12:08 UTC, kimfy commented on variables.tf
> +    principal_object_id = string
Shouldn't this be optional?

2024-06-11 20:32 UTC, SanderBlom commented
Closing this as we will add this functionality in the identity block

2024-06-11 20:32 UTC, closed without merging