feat: add an identity block to configure the workload identity
blinqas/station pull request #132
Opened 2024-06-12 06:33 UTC by SanderBlom

# Add an identity block to configure the workload identity 

## Description
This PR aims to add a identity block where we can configure the workload identity (identity that does terraform plan & apply). Today we have a few different variables and it would make more sense to group this functionality into one block imo.

## Type of Change

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update
- [x] Other

## Testing
See the testing [docs](../tests/readme.md) for more information about how to test your code 
- [ ] Performed a local `terraform plan`, `apply`, and `destroy` to validate changes.
- [ ] All tests are passing.
- [ ] Added, updated, or removed tests when appropriate

## Checklist

Before submitting this PR, please ensure the following:

- [ ] My commits follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) style guide
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings. I have ran `terraform validate` in the root module and all sub modules where I have made changes

## Additional Information

Provide any additional information or context about the pull request here.

---

Thank you for contributing to Station!

2025-02-08 20:42 UTC, kimfy commented on role_assignment.tf
> +locals {
@SanderBlom we need to look into this block to streamline further og clean up

2025-02-08 20:42 UTC, kimfy commented on role_assignment.tf
> +      // Her må du merge scope med alle de derre landing zone RGene
TODO: Remove

2025-02-12 14:01 UTC, kimfy requested changes

2025-02-12 14:01 UTC, kimfy commented on test/test_identity.tf
This file can be deleted

2025-02-12 14:01 UTC, kimfy commented on test/test_user_assigned_identities.tf
This file can be deleted

2025-02-12 14:01 UTC, kimfy commented on tests/identity.tftest.hcl
> +    condition     = true
Implement proper check

2025-02-12 14:01 UTC, kimfy commented on tests/identity.tftest.hcl
> +    condition     = true
Implement proper check

2025-02-12 14:01 UTC, kimfy commented on tests/identity.tftest.hcl
> +    condition     = true
Implement proper check

2025-02-12 14:01 UTC, kimfy commented on user_assigned_identity/role_assignments.tf
> +  for_each                               = { for key, value in var.role_assignments : key => value if value.scope != null }
The for_each can reference var.role_assignments directly without checks. This logic is handled in ../role_assignments.tf now (for the var.identity.role_assignments).

2025-02-12 14:01 UTC, kimfy commented on tests/setup-tfe-project/main.tf
> +  for_each         = var.create_ad_group ? { "test" = {} } : {}
😬

2025-02-14 10:21 UTC, kimfy commented on group_membership.tf
This file was removed as the same logic is applied @ user_assigned_identities.tf#21

2025-02-14 10:21 UTC, kimfy commented on application_federated_identity_credential.tf
This file ws removed because we decided to get rid of this feature. Configure this in the Landing Zone instead

2025-02-14 10:22 UTC, kimfy commented on test/test_user_assigned_identities.tf
This file was removed because testing has been moved to the Terraform test framework @ tests/identity.tftest.hcl

2025-02-14 10:22 UTC, kimfy approved these changes

2025-02-14 11:55 UTC, SanderBlom commented on variables.tf
> +    directory_role_assignment = optional(map(object({
We need to support both `role_name` and `role_id`

2025-02-19 11:16 UTC, merged