feat: support azuread_app_role_assignment on workload identity
blinqas/station pull request #133
Opened 2024-07-02 18:53 UTC by kimfy

# Support `azuread_app_role_assignment` on workload identity

## Description

This pull request adds support for Entra ID App Roles (built-in) on the workload identity. It also ensures the workload identity has permissions in the Entra ID directory to perform operations such as add on groups created with Station.

Fixes #105 

## Type of Change

- [x] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Other

## Testing
See the testing [docs](../tests/readme.md) for more information about how to test your code 
- [x] Performed a local `terraform plan`, `apply`, and `destroy` to validate changes.
- [x] All tests are passing.
- [x] Added, updated, or removed tests when appropriate

## Checklist

Before submitting this PR, please ensure the following:

- [x] My commits follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) style guide
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings. I have ran `terraform validate` in the root module and all sub modules where I have made changes

## Additional Information

N/A

---

Thank you for contributing to Station!

2024-07-02 18:54 UTC, kimfy commented on user_assigned_identities.tf
> +    toset(length(var.groups) == 0 ? [] : ["User.ReadBasic.All"])
It wasn't enough to compare `var.groups` to either of `{}` or `null` - I don't really know why. This is why I instead compare the length of the map to check if any groups are being created.

2024-07-03 06:35 UTC, SanderBlom requested changes
Add tests for the `app_role_assignments`

2024-07-04 16:27 UTC, kimfy commented
> Add tests for the `app_role_assignments`

La til `test/test_workload_identity.tf` - er det nok?

2024-07-05 06:09 UTC, SanderBlom approved these changes

2024-07-05 06:09 UTC, merged